#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-fExoticOptions
Version  : 3042.80
Release  : 4
URL      : https://cran.r-project.org/src/contrib/fExoticOptions_3042.80.tar.gz
Source0  : https://cran.r-project.org/src/contrib/fExoticOptions_3042.80.tar.gz
Summary  : Rmetrics - Pricing and Evaluating Exotic Option
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-fBasics
Requires: R-fOptions
Requires: R-timeDate
BuildRequires : R-fBasics
BuildRequires : R-fOptions
BuildRequires : R-timeDate
BuildRequires : clr-R-helpers

%description
barrier options, Asian options, binary options, currency 
    translated options, lookback options, multiple asset options
	and multiple exercise options.

%prep
%setup -q -c -n fExoticOptions

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1530471184

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1530471184
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library fExoticOptions
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library fExoticOptions
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library fExoticOptions
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library fExoticOptions|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/fExoticOptions/COPYRIGHT.html
/usr/lib64/R/library/fExoticOptions/DESCRIPTION
/usr/lib64/R/library/fExoticOptions/INDEX
/usr/lib64/R/library/fExoticOptions/Meta/Rd.rds
/usr/lib64/R/library/fExoticOptions/Meta/features.rds
/usr/lib64/R/library/fExoticOptions/Meta/hsearch.rds
/usr/lib64/R/library/fExoticOptions/Meta/links.rds
/usr/lib64/R/library/fExoticOptions/Meta/nsInfo.rds
/usr/lib64/R/library/fExoticOptions/Meta/package.rds
/usr/lib64/R/library/fExoticOptions/NAMESPACE
/usr/lib64/R/library/fExoticOptions/R/fExoticOptions
/usr/lib64/R/library/fExoticOptions/R/fExoticOptions.rdb
/usr/lib64/R/library/fExoticOptions/R/fExoticOptions.rdx
/usr/lib64/R/library/fExoticOptions/help/AnIndex
/usr/lib64/R/library/fExoticOptions/help/aliases.rds
/usr/lib64/R/library/fExoticOptions/help/fExoticOptions.rdb
/usr/lib64/R/library/fExoticOptions/help/fExoticOptions.rdx
/usr/lib64/R/library/fExoticOptions/help/paths.rds
/usr/lib64/R/library/fExoticOptions/html/00Index.html
/usr/lib64/R/library/fExoticOptions/html/R.css
/usr/lib64/R/library/fExoticOptions/unitTests/Makefile
/usr/lib64/R/library/fExoticOptions/unitTests/runTests.R
/usr/lib64/R/library/fExoticOptions/unitTests/runit.BarrierOptions.R
/usr/lib64/R/library/fExoticOptions/unitTests/runit.BasicAsianOptions.R
/usr/lib64/R/library/fExoticOptions/unitTests/runit.BinaryOptions.R
/usr/lib64/R/library/fExoticOptions/unitTests/runit.CurrencyTranslatedOptions.R
/usr/lib64/R/library/fExoticOptions/unitTests/runit.LookbackOptions.R
/usr/lib64/R/library/fExoticOptions/unitTests/runit.MultipleAssetsOptions.R
/usr/lib64/R/library/fExoticOptions/unitTests/runit.MultipleExercisesOptions.R
